### ISSUE TITLE
empty output cells

### ISSUE THREAD

**Issue by albertoruiz** [Calysto/octave_kernel#20]
This is another minor problem, possibly related to https://github.com/Calysto/octave_kernel/issues/18.

I think that commands or expressions with supressed output should not produce empty output cells.

**Comment by blink1073** [comment]
Fixed, thanks!

**Comment by xfliu** [comment]
I tested the latest version  '0.13.1', but there is still the same error, i.e., only the last line is printed.

Below is a very simple example to confirm:

x=[1,2]
x+1

**Comment by dsblank** [comment]
@xfliu This may be related to #18. Can you say what you would expect the output to be in this case? If the lines ended with a semicolon, then it should produce output, but otherwise it should?

```octave
octave:3> x=[1,2];
octave:4> x + 1
ans =

   2   3
```

**Comment by xfliu** [comment]
Just as you said:

If the lines ended with a semicolon, then it should not produce output, but otherwise it should.

Even using disp(x), only the last disp is produced.

Thanks.

**Comment by blink1073** [comment]
I narrowed it down to the way we are handling `REPLWrap`, it does indeed need a refactor.

**Comment by blink1073** [comment]
@xfliu, this should be fixed by `pip install --upgrade metakernel`
