### ISSUE TITLE
'SVG' object has no attribute 'encode'

### ISSUE THREAD

**Issue by hecate-xw** [Calysto/octave_kernel#30]
And i used jupyter notebook in chrome,
and when i ran 
```
t = linspace(0,6*pi,100);
plot(sin(t))
```
there were a problem: `'SVG' object has no attribute 'encode'`

The environment: 
```
Ubuntu 14.04
jupyter 4.0.6
octave 3.8.1
gunplot 4.6
octave_kernel 0.13.2
metakernel  0.11.8
```

I viewed octave_kernel.py and found code about 'svg', maybe in the past octave_kernel used png,
So it encounters?

I forgot to say that if i don't use plot, it works well.
> And i have installed gnuplot, octave-plot and octave-geometry and so on.

And I tried the solution in <https://github.com/Calysto/octave_kernel/issues/6>, 
but didn't solved.

![000](https://cloud.githubusercontent.com/assets/6323054/11957394/8236d526-a8fc-11e5-8ec9-4c8cb8e0f8fe.png)

![001](https://cloud.githubusercontent.com/assets/6323054/11957437/c96513c2-a8fc-11e5-9796-2c5760974214.png)

![002](https://cloud.githubusercontent.com/assets/6323054/11957469/e882733a-a8fc-11e5-80cc-e6731aa62bbe.png)

The plot shows correctly in a new window which means test.png was created correctly.

**Comment by blink1073** [comment]
Hi @hecate-xw, sorry, I missed this one.  What operating system and which version of python are you running?

**Comment by blink1073** [comment]
You might also try `pip install -U octave_kernel` and see if we have already fixed it in recent releases.

**Comment by hecate-xw** [comment]
@blink1073  Thank you.

I used ubuntu 14.04 with python 2.7.6 on a VPS.

And i thried `pip install -U octave_kernel`, but there is still the same error.

**Comment by blink1073** [comment]
Hmm, I tried with Python 2.7 and it still works, but I am on OSX.

Does the following work for you with an SVG image?

```
from IPython.display import SVG
SVG('my_file.svg')
```

**Comment by blink1073** [comment]
(using the default Python kernel)

**Comment by hecate-xw** [comment]
The result is:

![result](https://cloud.githubusercontent.com/assets/6323054/12221811/ac33d65c-b7e4-11e5-92ca-67709a8f48f6.png)

It works well.

Wmmm, I would try to fix it by myself if it is the environment that cause this problem .

**Comment by blink1073** [comment]
Can you give the whole traceback that is printed in the terminal?

**Comment by hecate-xw** [comment]
umm, there's no traceback, Only one line:
`Out[4]: <IPython.core.display.SVG object>`

**Comment by blink1073** [comment]
Sorry, I mean when you run the original code in an Octave Kernel, is anything printed to the terminal where you launched the notebook?

**Comment by hecate-xw** [comment]
Sorry for misunderstanding.

when i click into OctaveTest.ipynb on browser, the terminal shows:
```
Kernel started: 018e123f-cbe7-4233-afb7-255cc1170c4b
/usr/local/lib/python2.7/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
"`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
```
But i think it has no impact because there's same messages with other kernels.

Then when i run
```
t = 1:10
plot(sin(t))
```

The terminal only displays:
`gnuplot 4.6 patchlevel 4`
there's no other error messages.
and the browser still print `'SVG' object has no attribute 'encode'`.

**Comment by blink1073** [comment]
Can you try making this change?  If it works, it probably means that your SVG images will always be the same size regardless of setting:

```diff
--- a/octave_kernel.py
+++ b/octave_kernel.py
@@ -112,16 +112,7 @@ class OctaveKernel(ProcessMetaKernel):
             for fname in os.listdir(plot_dir):
                 filename = os.path.join(plot_dir, fname)
                 try:
-                    if fname.lower().endswith('.svg'):
-                        im = SVG(filename)
-                        if ',' in self.plot_settings['size']:
-                            size = self.plot_settings['size']
-                            width, height = size.split(',')
-                            width, height = int(width), int(height)
-                            im.data = self._fix_gnuplot_svg_size(im.data,
-                                size=(width, height))
-                    else:
-                        im = Image(filename)
+                    im = Image(filename)
                     self.Display(im)
                 except Exception as e:
                     self.Error(e)
```

**Comment by hecate-xw** [comment]
I tried the change, and now when I run
```
t = 1:10;
plot(sin(t))
```
Browser shows:
`Cannot embed the 'svg' image format`
and terminal still only shows 
`gnuplot 4.6 patchlevel 4`

**Comment by blink1073** [comment]
How about this?

```diff
--- a/octave_kernel.py
+++ b/octave_kernel.py
@@ -92,6 +92,7 @@ class OctaveKernel(ProcessMetaKernel):
             self._first = False
             if sys.platform == 'darwin':
                 self.plot_settings['format'] = 'svg'
+            self.plot_settings['format'] = 'png'
             self.handle_plot_settings()
             super(OctaveKernel, self).do_execute_direct(self._setup)
             if os.name != 'nt':

**Comment by hecate-xw** [comment]
Now it shows
`'Image' object has no attribute 'encode'`
If I recover the following code:
```
-                    if fname.lower().endswith('.svg'):
-                        im = SVG(filename)
-                        if ',' in self.plot_settings['size']:
-                            size = self.plot_settings['size']
-                            width, height = size.split(',')
-                            width, height = int(width), int(height)
-                            im.data = self._fix_gnuplot_svg_size(im.data,
-                                size=(width, height))
-                    else:
-                        im = Image(filename)
```
still `'Image' object has no attribute 'encode'`

**Comment by blink1073** [comment]
I'm afraid I'm out of ideas.

**Comment by hecate-xw** [comment]
Thanks a lot...
I would try to solve it as i'm in leisure.

**Comment by williamstein** [comment]
For what it is worth, I have precisely the same problem with the Octave kernel on https://cloud.sagemath.com (a site which I run).  You can replicate the same problem in 2 minutes by making an SMC account, making a project, and clicking +"New" --> Jupyter Kernel, and switching to the Octave kernel.    The site is running Ubuntu 15.10 with standard Gnuplot, etc.

**Comment by dsblank** [comment]
Thanks William. Trying this inside the Octave kernel:

```
%%python

import tempfile
import os

self = kernel
print(1)
kernel.do_execute_direct("plot(sin(t))")
print(2)
if self.plot_settings.get('backend', None) == 'inline':
    plot_dir = tempfile.mkdtemp()
    self._make_figs(plot_dir)
    width, height = 0, 0
    for fname in os.listdir(plot_dir):
        filename = os.path.join(plot_dir, fname)
        print(filename)
        if fname.lower().endswith('.svg'):
            im = SVG(filename)
            if ',' in self.plot_settings['size']:
                size = self.plot_settings['size']
                width, height = size.split(',')
                width, height = int(width), int(height)
                im.data = self._fix_gnuplot_svg_size(im.data,
                    size=(width, height))
        else:
            im = Image(filename)
        self.Display(im)
```

Gives this result:
```
1
'SVG' object has no attribute 'encode'
2
```

Which shows that this is happening in `do_execute_direct`, not in the following code.

**Comment by dsblank** [comment]
No, I think I am wrong. I'm not sure how to test to see what is wrong.

**Comment by minrk** [comment]
I think I found the problem; it's [this](https://github.com/Calysto/metakernel/commit/cf80aad9#diff-2b6c4467f650340a93939f404cc508b2R41) call (on Python 2), which appears to assume that `self.repr` is only ever called on text, but this is not true here. `self.Display` uses `self.repr` to populate `text/plain`. On Python 2, this means calling `SVG(...).encode('utf8')`.

Calysto/metakernel#87 should fix that bug, at least.

 I'm not 100% sure what the *right* fix is, if the assumption that repr is only called on text is as it should be, then a context manager in octave_kernel switching back to the default repr might be the way to go.

I suspect, though, that the don't-add-quotes repr=str bit in ProcessMetaKernel isn't the best way to remove the quotation marks around output coming from the subprocess.

**Comment by minrk** [comment]
I opened an alternate proposal in Calysto/metakernel#88 which solves the problem in a different way, by wrapping text output in a special object, removing the need for overriding the default `repr` method.

**Comment by dsblank** [comment]
Thanks @minrk ! I'll get with @blink1073 and figure out what a better solution is overall.

**Comment by minrk** [comment]
I think the second solution is better because it confines the quote-handling to subprocess output explicitly, rather than assuming all output comes from the subprocess by default.

**Comment by minrk** [comment]
Related to debugging future problems like this, it might be appropriate to log more information when display fails than just calling `self.Error` with the string of the error message.

**Comment by hecate-xw** [comment]
Thanks @minrk
